In [2]:
import numpy as np 

#### 基本属性
* ndarray.ndim  维度  
* ndarray.shape   形状  
* ndarray.size   元素总个数  
* ndarray.dtype  数据类型 numpy自定义类型 int32, float64..  
* ndarray.itemsize  每个元素占用字节  
* ndarray.data  包含数组实际元素的缓冲区

In [3]:
a = np.arange(15).reshape(3, 5)
a

In [4]:
a.ndim

In [5]:
a.shape

In [6]:
a.size

In [7]:
a.data

In [8]:
a.dtype.name

#### 数组创建
默认数据类型为 numpy.float64
* np.array  从list或tuple创建ndarray，默认数据类型从原始数据推测  
* np.zeros  填充0  
* np.ones  填充1  
* np.empty  随机初始化值，值依赖内存状态  
* np.arange(start, end, step)  序列数组  
* np.linspace(start, end, nums)  线性均匀分布

#### 数组打印
```
np.set_printoptions(threshold=sys.maxsize)  # 设置数组打印时显示所有元素
np.set_printoptions(threshold=1000)   # 还原为默认
```
* 最后一个轴从左到右打印  
* 其余从上到下打印,每个切片直接用空行分隔

In [9]:
np.arange(24).reshape(1, 2, 3, 4)

In [10]:
np.arange(10000).reshape(100, 100)

#### 基本操作

In [11]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [12]:
a - b

In [13]:
b ** 2

In [14]:
A = np.array([[1, 1],
[0, 1]])
B = np.array([[2, 0],
[3, 4]])

In [15]:
# * 点积  对应位置元素相乘
A * B

In [16]:
# 矩阵相乘 @(python>=3.5) or dot
A @ B

In [17]:
A.dot(B)

In [18]:
A.dot(B)

#### 索引、切片与迭代
index可以从 **-1** 开始，表示从最后一个元素开始
* 索引 array\[index\]  
* 切片 array\[start, end, step\]  不包含 end  
* 多维数组每个轴可以有一个索引。这些索引以元组给出，并用逗号分隔
* 多维数组切片操作中，产生完整索引的多个 **:** 可以换位 ...

In [19]:
a = np.arange(10) ** 3
a

In [20]:
a[2]

In [21]:
a[2:5]  # 前闭后开

In [22]:
a[2:8:2]

In [23]:
a[::-1]  # 反转

In [24]:
c = np.array([[[0, 1, 2], 
                [10, 12, 13]],
                [[100, 101, 102],
                [110, 112, 113]]])
c.shape

In [25]:
c[1, ...]   # c[1, :, :] or c[1]

In [26]:
c[..., 2]  # c[:, :, 2]

#### 数组形状操作
* ravel(order='C|F')   # 拍平 默认 C  
* reshape    # 修改形状 修改后的size和原来的size需要保持一致  
* T   # 转置  

In [38]:
a = np.floor(10 * np.random.random((3, 4)))
a

array([[4., 9., 5., 9.],
       [6., 0., 1., 9.],
       [5., 7., 1., 6.]])

In [31]:
a.ravel(order='F')

#### 

In [41]:
a = np.floor(10*np.random.random((2, 2)))
a

array([[8., 9.],
       [5., 7.]])

In [42]:
b = np.floor(10*np.random.random((2, 2)))
b

array([[9., 7.],
       [1., 9.]])

In [43]:
np.vstack((a, b))

array([[8., 9.],
       [5., 7.],
       [9., 7.],
       [1., 9.]])

In [44]:
np.hstack((a, b))

array([[8., 9., 9., 7.],
       [5., 7., 1., 9.]])

In [45]:
a = np.floor(10*np.random.random((2, 12)))
a

array([[6., 4., 4., 8., 3., 4., 6., 0., 2., 6., 3., 5.],
       [1., 6., 7., 7., 3., 1., 2., 5., 9., 3., 5., 6.]])

In [46]:
np.hsplit(a, 3)

[array([[6., 4., 4., 8.],
        [1., 6., 7., 7.]]), array([[3., 4., 6., 0.],
        [3., 1., 2., 5.]]), array([[2., 6., 3., 5.],
        [9., 3., 5., 6.]])]

#### 数组副本或视图
> 视图
>> a = np.arange(2) b = a   

* view 浅层视图  引用的数组会关联修改
* copy  深层视图  引用的数组不会关联修改

In [47]:
a = np.arange(12)
b = a

In [48]:
b is a

True

In [49]:
c = a.view()
c is a

False

In [50]:
c.base is a

True

In [51]:
d = a.copy()
d is a

False

In [52]:
d.base is a

False

In [54]:
d[0] = 9999
d

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [55]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 索引
* 花式索引  
* 布尔索引

In [57]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])

In [58]:
a[i]

array([ 1,  1,  9, 64, 25])

In [59]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [60]:
a = np.arange(12).reshape(3, 4)
b = a > 4

In [61]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])